#!/bin/sh

# Package feeds
# ImmortalWrt 25.12+ uses apk; 24.10 and older use opkg.  The third-party
# feeds below are build-time source feeds and are not published on the
# official download server, so remove those generated entries.  Keep the
# official ImmortalWrt feed: OpenWrt and ImmortalWrt packages are not
# interchangeable.
if [ -f /etc/apk/repositories.d/distfeeds.list ]; then
    sed -i -e '/kenzo/d' -e '/mosdns/d' -e '/small/d' \
        -e '/nikki/d' -e '/momo/d' -e '/helloworld/d' -e '/video/d' \
        /etc/apk/repositories.d/distfeeds.list
    # If you host your own ABI-compatible package index, add it here:
    # echo 'https://example.com/openwrt/packages/aarch64_cortex-a53/packages.adb' \
    #     >> /etc/apk/repositories.d/customfeeds.list
elif [ -f /etc/opkg/distfeeds.conf ]; then
    sed -i -e '/kenzo/d' -e '/mosdns/d' -e '/small/d' \
        -e '/nikki/d' -e '/momo/d' -e '/helloworld/d' -e '/video/d' \
        /etc/opkg/distfeeds.conf
fi
#echo "mt7915e wed_enable=Y" >> /etc/modules.d/mt7915e

# Make sure the copied DHCP/RA guard script is executable and loaded by fw4.
chmod 0755 /etc/firewall/dhcp_guard.sh 2>/dev/null || true
if ! uci -q get firewall.custom_rules >/dev/null 2>&1; then
    uci add firewall include >/dev/null
    uci rename firewall.@include[-1]='custom_rules'
fi
uci set firewall.custom_rules.type='script'
uci set firewall.custom_rules.path='/etc/firewall.user'
uci set firewall.custom_rules.fw4_compatible='1'
uci set firewall.custom_rules.enabled='1'
uci commit firewall

[ "$(uci -q get system.@system[0].init)" != "" ] &&  exit 0
#set lan ip
uci set network.lan.ipaddr='192.168.71.80'
uci commit network

uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].cronloglevel='8'
uci set system.@system[0].conloglevel='7'
uci set system.@system[0].init='initiated'
uci commit system

#set luci default language
uci set luci.main.lang='zh_cn'
uci commit luci

#enable wlan
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-device[1].disabled='0'
uci set wireless.@wifi-iface[1].disabled='0'
uci set wireless.@wifi-device[0].country='CN'
uci set wireless.@wifi-device[0].channel='auto'
uci set wireless.@wifi-iface[0].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[0].key='12345678'
uci set wireless.@wifi-iface[0].ieee80211r='1'
uci set wireless.@wifi-iface[0].mobility_domain='1111'
uci set wireless.@wifi-iface[0].reassociation_deadline='20000'
uci set wireless.@wifi-iface[0].ft_over_ds='0'
uci set wireless.@wifi-iface[0].ft_psk_generate_local='1'
uci set wireless.@wifi-iface[0].ssid='Openwrt'
uci set wireless.@wifi-device[1].country='CN'
uci set wireless.@wifi-device[1].channel='auto'
uci set wireless.@wifi-device[1].htmode='HE160'
uci set wireless.@wifi-iface[1].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[1].key='12345678'
uci set wireless.@wifi-iface[1].ieee80211r='1'
uci set wireless.@wifi-iface[1].mobility_domain='1111'
uci set wireless.@wifi-iface[1].reassociation_deadline='20000'
uci set wireless.@wifi-iface[1].ft_over_ds='0'
uci set wireless.@wifi-iface[1].ft_psk_generate_local='1'
uci set wireless.@wifi-iface[1].ssid='Openwrt5G'
uci commit wireless

#enable flow offloading
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci commit firewall




echo "/www/luci-static/argon/background/" >> /etc/sysupgrade.conf
exit 0
